# Generated by Django 3.2.9 on 2021-11-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.IntegerField(null=True)),
                ('product_id', models.IntegerField(null=True)),
                ('sku_name', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('manufacturer_name', models.CharField(max_length=100, null=True)),
                ('salt_name', models.CharField(max_length=100, null=True)),
                ('drug_form', models.CharField(max_length=100, null=True)),
                ('Pack_size', models.CharField(max_length=100, null=True)),
                ('strength', models.CharField(max_length=100, null=True)),
                ('product_banned_flag', models.BooleanField(null=True)),
                ('unit', models.CharField(max_length=100, null=True)),
                ('price_per_unit', models.IntegerField(null=True)),
            ],
        ),
    ]
