# Generated by Django 3.2.9 on 2021-11-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meds',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
